import styles from "./App.module.scss";
import NavBar from "./components/NavBar/NavBar";
import Card from "./components/Card/Card";
import _ from "lodash";
import classNames from "classnames";
import MobileApp from "./components/MobileApp/MobileApp";

const payIn = 50;
const teamCount = 10;
const payoutConstant = 3.26;

const PlayerCard = ({
    name,
    position,
    team,
    keeperValueForCurrentTeam: keeperCost,
    ...r
}) => {
    const teamColors = {
        ARI: "#9b2743",
        ATL: "#a6192e",
        BAL: "#241773",
        BUF: "#c60c30",
        CAR: "#0085ca",
        CHI: "#c83803",
        CIN: "#fc4c02",
        CLE: "#fb4f14",
        DAL: "#b0b7bc",
        DEN: "#0c2340",
        DET: "#0069b1",
        GB: "#ffb611",
        HOU: "#a71930",
        IND: "#a5acaf",
        JAX: "#9f792c",
        KC: "#ffb611",
        LAC: "#127dc5",
        LAR: "#063992",
        LV: "#87909a",
        MIA: "#008c95",
        MIN: "#ffc72c",
        NE: "#c60c30",
        NO: "#9f8958",
        NYJ: "#115740",
        NYG: "#a71930",
        PHI: "#a5acaf",
        PIT: "#ffb81c",
        SEA: "#69be29",
        SF: "#b3995d",
        TB: "#c91331",
        TEN: "#4b92db",
    };

    return (
        <div className={styles.playerCard}>
            <div className={styles.left}>
                <div
                    className={styles.imageContainer}
                    style={{ backgroundColor: teamColors[team] }}
                >
                    <img
                        className={styles.playerImage}
                        src="../public/images/justin-fields.png"
                    />
                </div>

                <div className={styles.playerInfo}>
                    <div className={styles.playerName}>{name}</div>
                    <div className={styles.playerDetails}>
                        <div
                            className={classNames(
                                styles.position,
                                styles[position]
                            )}
                        >
                            {position}
                        </div>
                        <div className={styles.divider}>|</div>
                        <div
                            className={styles.position}
                            style={{
                                color: teamColors[team],
                                borderColor: teamColors[team],
                            }}
                        >
                            {team}
                        </div>
                    </div>
                </div>
            </div>
            <div className={styles.right}>
                <div className={styles.keeperCost}>{keeperCost}th</div>
                <div className={styles.roundLabel}>Round Pick</div>
                <div className={styles.roundLabel}>Round Pick</div>
            </div>
        </div>
    );
};

const data = {
    1: [
        {
            playerId: "1479",
            team: "LAC",
            adp: 39,
            adr: 4,
            name: "Keenan Allen",
            position: "WR",
            keeperValueForCurrentTeam: 1,
            diff: 3,
            rosteredBy: "Darius",
        },
        {
            playerId: "167",
            team: null,
            adp: 325,
            adr: 28,
            name: "Tom Brady",
            position: "QB",
            keeperValueForCurrentTeam: 3,
            diff: 25,
            rosteredBy: "Darius",
        },
        {
            playerId: "4029",
            team: null,
            adp: 58,
            adr: 5,
            name: "Dalvin Cook",
            position: "RB",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "Darius",
        },
        {
            playerId: "4034",
            team: "SF",
            adp: 2.3,
            adr: 1,
            name: "Christian McCaffrey",
            position: "RB",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "Darius",
        },
        {
            playerId: "4089",
            team: "LAC",
            adp: 162.3,
            adr: 14,
            name: "Gerald Everett",
            position: "TE",
            keeperValueForCurrentTeam: 15,
            diff: -1,
            rosteredBy: "Darius",
        },
        {
            playerId: "4137",
            team: "ARI",
            adp: 74,
            adr: 7,
            name: "James Conner",
            position: "RB",
            keeperValueForCurrentTeam: 2,
            diff: 5,
            rosteredBy: "Darius",
        },
        {
            playerId: "4866",
            team: "NYG",
            adp: 10.7,
            adr: 1,
            name: "Saquon Barkley",
            position: "RB",
            keeperValueForCurrentTeam: 1,
            diff: 0,
            rosteredBy: "Darius",
        },
        {
            playerId: "5022",
            team: "PHI",
            adp: 73,
            adr: 7,
            name: "Dallas Goedert",
            position: "TE",
            keeperValueForCurrentTeam: 11,
            diff: -4,
            rosteredBy: "Darius",
        },
        {
            playerId: "5937",
            team: "PIT",
            adp: 67.3,
            adr: 6,
            name: "Diontae Johnson",
            position: "WR",
            keeperValueForCurrentTeam: 4,
            diff: 2,
            rosteredBy: "Darius",
        },
        {
            playerId: "7042",
            team: "BUF",
            adp: null,
            adr: null,
            name: "Tyler Bass",
            position: "K",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "Darius",
        },
        {
            playerId: "7523",
            team: "JAX",
            adp: 59.3,
            adr: 5,
            name: "Trevor Lawrence",
            position: "QB",
            keeperValueForCurrentTeam: 9,
            diff: -4,
            rosteredBy: "Darius",
        },
        {
            playerId: "7588",
            team: "DEN",
            adp: 81.3,
            adr: 7,
            name: "Javonte Williams",
            position: "RB",
            keeperValueForCurrentTeam: 4,
            diff: 3,
            rosteredBy: "Darius",
        },
        {
            playerId: "7601",
            team: "ARI",
            adp: 137.3,
            adr: 12,
            name: "Rondale Moore",
            position: "WR",
            keeperValueForCurrentTeam: 13,
            diff: -1,
            rosteredBy: "Darius",
        },
        {
            playerId: "8112",
            team: "ATL",
            adp: 55,
            adr: 5,
            name: "Drake London",
            position: "WR",
            keeperValueForCurrentTeam: 7,
            diff: -2,
            rosteredBy: "Darius",
        },
        {
            playerId: "8136",
            team: "TB",
            adp: 67.7,
            adr: 6,
            name: "Rachaad White",
            position: "RB",
            keeperValueForCurrentTeam: 7,
            diff: -1,
            rosteredBy: "Darius",
        },
        {
            playerId: "8160",
            team: "PIT",
            adp: 149.3,
            adr: 13,
            name: "Kenny Pickett",
            position: "QB",
            keeperValueForCurrentTeam: 14,
            diff: -1,
            rosteredBy: "Darius",
        },
        {
            playerId: "8183",
            team: "SF",
            adp: 183.7,
            adr: 16,
            name: "Brock Purdy",
            position: "QB",
            keeperValueForCurrentTeam: 17,
            diff: -1,
            rosteredBy: "Darius",
        },
        {
            playerId: "8205",
            team: "KC",
            adp: 77.7,
            adr: 7,
            name: "Isiah Pacheco",
            position: "RB",
            keeperValueForCurrentTeam: 8,
            diff: -1,
            rosteredBy: "Darius",
        },
        {
            playerId: "SF",
            team: "SF",
            adp: 144.5,
            adr: 13,
            name: "SF DST",
            position: "DEF",
            keeperValueForCurrentTeam: 14,
            diff: -1,
            rosteredBy: "Darius",
        },
    ],
    2: [
        {
            playerId: "4718",
            team: "HOU",
            adp: null,
            adr: null,
            name: "Dare Ogunbowale",
            position: "RB",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "Zack",
        },
        {
            playerId: "4881",
            team: "BAL",
            adp: 38.7,
            adr: 4,
            name: "Lamar Jackson",
            position: "QB",
            keeperValueForCurrentTeam: 3,
            diff: 1,
            rosteredBy: "Zack",
        },
        {
            playerId: "5012",
            team: "BAL",
            adp: 33.3,
            adr: 3,
            name: "Mark Andrews",
            position: "TE",
            keeperValueForCurrentTeam: 3,
            diff: 0,
            rosteredBy: "Zack",
        },
        {
            playerId: "5230",
            team: "DET",
            adp: null,
            adr: null,
            name: "Michael Badgley",
            position: "K",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "Zack",
        },
        {
            playerId: "5880",
            team: "NYG",
            adp: 196,
            adr: 17,
            name: "Parris Campbell",
            position: "WR",
            keeperValueForCurrentTeam: 18,
            diff: -1,
            rosteredBy: "Zack",
        },
        {
            playerId: "5890",
            team: "BUF",
            adp: 114.3,
            adr: 10,
            name: "Damien Harris",
            position: "RB",
            keeperValueForCurrentTeam: 11,
            diff: -1,
            rosteredBy: "Zack",
        },
        {
            playerId: "6783",
            team: "DEN",
            adp: 51.3,
            adr: 5,
            name: "Jerry Jeudy",
            position: "WR",
            keeperValueForCurrentTeam: 6,
            diff: -1,
            rosteredBy: "Zack",
        },
        {
            playerId: "6797",
            team: "LAC",
            adp: 48.3,
            adr: 5,
            name: "Justin Herbert",
            position: "QB",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "Zack",
        },
        {
            playerId: "6828",
            team: "GB",
            adp: 91,
            adr: 8,
            name: "AJ Dillon",
            position: "RB",
            keeperValueForCurrentTeam: 8,
            diff: 0,
            rosteredBy: "Zack",
        },
        {
            playerId: "6984",
            team: "DEN",
            adp: null,
            adr: null,
            name: "Tony Jones",
            position: "RB",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "Zack",
        },
        {
            playerId: "7083",
            team: "BAL",
            adp: 315,
            adr: 27,
            name: "Tyler Huntley",
            position: "QB",
            keeperValueForCurrentTeam: 18,
            diff: 9,
            rosteredBy: "Zack",
        },
        {
            playerId: "7528",
            team: "PIT",
            adp: 30.3,
            adr: 3,
            name: "Najee Harris",
            position: "RB",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "Zack",
        },
        {
            playerId: "7564",
            team: "CIN",
            adp: 2.7,
            adr: 1,
            name: "Ja'Marr Chase",
            position: "WR",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "Zack",
        },
        {
            playerId: "7611",
            team: "NE",
            adp: 25.7,
            adr: 3,
            name: "Rhamondre Stevenson",
            position: "RB",
            keeperValueForCurrentTeam: 11,
            diff: -8,
            rosteredBy: "Zack",
        },
        {
            playerId: "8129",
            team: "HOU",
            adp: 56.3,
            adr: 5,
            name: "Dameon Pierce",
            position: "RB",
            keeperValueForCurrentTeam: 7,
            diff: -2,
            rosteredBy: "Zack",
        },
        {
            playerId: "8144",
            team: "NO",
            adp: 27.7,
            adr: 3,
            name: "Chris Olave",
            position: "WR",
            keeperValueForCurrentTeam: 8,
            diff: -5,
            rosteredBy: "Zack",
        },
        {
            playerId: "BUF",
            team: "BUF",
            adp: 178,
            adr: 15,
            name: "BUF DST",
            position: "DEF",
            keeperValueForCurrentTeam: 15,
            diff: 0,
            rosteredBy: "Zack",
        },
        {
            playerId: "NE",
            team: "NE",
            adp: 166,
            adr: 14,
            name: "NE DST",
            position: "DEF",
            keeperValueForCurrentTeam: 15,
            diff: -1,
            rosteredBy: "Zack",
        },
    ],
    3: [
        {
            playerId: "2309",
            team: "CLE",
            adp: 39.7,
            adr: 4,
            name: "Amari Cooper",
            position: "WR",
            keeperValueForCurrentTeam: 6,
            diff: -2,
            rosteredBy: "Nick",
        },
        {
            playerId: "3321",
            team: "MIA",
            adp: 6,
            adr: 1,
            name: "Tyreek Hill",
            position: "WR",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "Nick",
        },
        {
            playerId: "4018",
            team: "CIN",
            adp: 46.7,
            adr: 4,
            name: "Joe Mixon",
            position: "RB",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "Nick",
        },
        {
            playerId: "4046",
            team: "KC",
            adp: 20,
            adr: 2,
            name: "Patrick Mahomes",
            position: "QB",
            keeperValueForCurrentTeam: 2,
            diff: 0,
            rosteredBy: "Nick",
        },
        {
            playerId: "4082",
            team: "WAS",
            adp: 190.3,
            adr: 16,
            name: "Curtis Samuel",
            position: "WR",
            keeperValueForCurrentTeam: 17,
            diff: -1,
            rosteredBy: "Nick",
        },
        {
            playerId: "4147",
            team: "DEN",
            adp: 103,
            adr: 9,
            name: "Samaje Perine",
            position: "RB",
            keeperValueForCurrentTeam: 10,
            diff: -1,
            rosteredBy: "Nick",
        },
        {
            playerId: "4892",
            team: "TB",
            adp: 218,
            adr: 19,
            name: "Baker Mayfield",
            position: "QB",
            keeperValueForCurrentTeam: 18,
            diff: 1,
            rosteredBy: "Nick",
        },
        {
            playerId: "5001",
            team: "HOU",
            adp: 121.7,
            adr: 11,
            name: "Dalton Schultz",
            position: "TE",
            keeperValueForCurrentTeam: 6,
            diff: 5,
            rosteredBy: "Nick",
        },
        {
            playerId: "5038",
            team: "DAL",
            adp: 168.7,
            adr: 15,
            name: "Michael Gallup",
            position: "WR",
            keeperValueForCurrentTeam: 15,
            diff: 0,
            rosteredBy: "Nick",
        },
        {
            playerId: "5089",
            team: "MIA",
            adp: 275,
            adr: 23,
            name: "Mike White",
            position: "QB",
            keeperValueForCurrentTeam: 18,
            diff: 5,
            rosteredBy: "Nick",
        },
        {
            playerId: "650",
            team: "NE",
            adp: null,
            adr: null,
            name: "Nick Folk",
            position: "K",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "Nick",
        },
        {
            playerId: "6826",
            team: "CHI",
            adp: 135.7,
            adr: 12,
            name: "Cole Kmet",
            position: "TE",
            keeperValueForCurrentTeam: 13,
            diff: -1,
            rosteredBy: "Nick",
        },
        {
            playerId: "6955",
            team: null,
            adp: 253.5,
            adr: 22,
            name: "James Robinson",
            position: "RB",
            keeperValueForCurrentTeam: 15,
            diff: 7,
            rosteredBy: "Nick",
        },
        {
            playerId: "7538",
            team: "NYJ",
            adp: 329,
            adr: 28,
            name: "Zach Wilson",
            position: "QB",
            keeperValueForCurrentTeam: 18,
            diff: 10,
            rosteredBy: "Nick",
        },
        {
            playerId: "7547",
            team: "DET",
            adp: 16,
            adr: 2,
            name: "Amon-Ra St. Brown",
            position: "WR",
            keeperValueForCurrentTeam: 5,
            diff: -3,
            rosteredBy: "Nick",
        },
        {
            playerId: "8146",
            team: "NYJ",
            adp: 18.3,
            adr: 2,
            name: "Garrett Wilson",
            position: "WR",
            keeperValueForCurrentTeam: 8,
            diff: -6,
            rosteredBy: "Nick",
        },
        {
            playerId: "8151",
            team: "SEA",
            adp: 39.3,
            adr: 4,
            name: "Kenneth Walker",
            position: "RB",
            keeperValueForCurrentTeam: 6,
            diff: -2,
            rosteredBy: "Nick",
        },
        {
            playerId: "PHI",
            team: "PHI",
            adp: 153,
            adr: 13,
            name: "PHI DST",
            position: "DEF",
            keeperValueForCurrentTeam: 14,
            diff: -1,
            rosteredBy: "Nick",
        },
    ],
    4: [
        {
            playerId: "1373",
            team: "SEA",
            adp: 104,
            adr: 9,
            name: "Geno Smith",
            position: "QB",
            keeperValueForCurrentTeam: 10,
            diff: -1,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "2216",
            team: "TB",
            adp: 70,
            adr: 6,
            name: "Mike Evans",
            position: "WR",
            keeperValueForCurrentTeam: 2,
            diff: 4,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "2505",
            team: "NYG",
            adp: 78.3,
            adr: 7,
            name: "Darren Waller",
            position: "TE",
            keeperValueForCurrentTeam: 4,
            diff: 3,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "3198",
            team: "TEN",
            adp: 21.7,
            adr: 2,
            name: "Derrick Henry",
            position: "RB",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "4035",
            team: "NO",
            adp: 99,
            adr: 9,
            name: "Alvin Kamara",
            position: "RB",
            keeperValueForCurrentTeam: 1,
            diff: 8,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "4068",
            team: "LAC",
            adp: 56.3,
            adr: 5,
            name: "Mike Williams",
            position: "WR",
            keeperValueForCurrentTeam: 9,
            diff: -4,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "4227",
            team: "KC",
            adp: null,
            adr: null,
            name: "Harrison Butker",
            position: "K",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "5045",
            team: "DEN",
            adp: 93,
            adr: 8,
            name: "Courtland Sutton",
            position: "WR",
            keeperValueForCurrentTeam: 6,
            diff: 2,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "5870",
            team: "NYG",
            adp: 95,
            adr: 8,
            name: "Daniel Jones",
            position: "QB",
            keeperValueForCurrentTeam: 13,
            diff: -5,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "5985",
            team: "NO",
            adp: null,
            adr: null,
            name: "Foster Moreau",
            position: "TE",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "6151",
            team: "CAR",
            adp: 58.7,
            adr: 5,
            name: "Miles Sanders",
            position: "RB",
            keeperValueForCurrentTeam: 9,
            diff: -4,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "6770",
            team: "CIN",
            adp: 37,
            adr: 4,
            name: "Joe Burrow",
            position: "QB",
            keeperValueForCurrentTeam: 3,
            diff: 1,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "6819",
            team: "IND",
            adp: 58,
            adr: 5,
            name: "Michael Pittman",
            position: "WR",
            keeperValueForCurrentTeam: 7,
            diff: -2,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "7591",
            team: "CHI",
            adp: 46.3,
            adr: 4,
            name: "Justin Fields",
            position: "QB",
            keeperValueForCurrentTeam: 6,
            diff: -2,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "7608",
            team: "CHI",
            adp: 108.7,
            adr: 10,
            name: "Khalil Herbert",
            position: "RB",
            keeperValueForCurrentTeam: 17,
            diff: -7,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "8154",
            team: "WAS",
            adp: 97.7,
            adr: 9,
            name: "Brian Robinson",
            position: "RB",
            keeperValueForCurrentTeam: 11,
            diff: -2,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "8167",
            team: "GB",
            adp: 54.7,
            adr: 5,
            name: "Christian Watson",
            position: "WR",
            keeperValueForCurrentTeam: 6,
            diff: -1,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "MIA",
            team: "MIA",
            adp: 209,
            adr: 18,
            name: "MIA DST",
            position: "DEF",
            keeperValueForCurrentTeam: 18,
            diff: 0,
            rosteredBy: "Jeremiah",
        },
        {
            playerId: "WAS",
            team: "WAS",
            adp: 244.5,
            adr: 21,
            name: "WAS DST",
            position: "DEF",
            keeperValueForCurrentTeam: 18,
            diff: 3,
            rosteredBy: "Jeremiah",
        },
    ],
    5: [
        {
            playerId: "1234",
            team: "DEN",
            adp: 114.7,
            adr: 10,
            name: "Russell Wilson",
            position: "QB",
            keeperValueForCurrentTeam: 3,
            diff: 7,
            rosteredBy: "Bob",
        },
        {
            playerId: "1426",
            team: null,
            adp: 44.7,
            adr: 4,
            name: "DeAndre Hopkins",
            position: "WR",
            keeperValueForCurrentTeam: 6,
            diff: -2,
            rosteredBy: "Bob",
        },
        {
            playerId: "1535",
            team: "ATL",
            adp: 202.3,
            adr: 17,
            name: "Cordarrelle Patterson",
            position: "RB",
            keeperValueForCurrentTeam: 9,
            diff: 8,
            rosteredBy: "Bob",
        },
        {
            playerId: "2028",
            team: "NO",
            adp: 127.7,
            adr: 11,
            name: "Derek Carr",
            position: "QB",
            keeperValueForCurrentTeam: 4,
            diff: 7,
            rosteredBy: "Bob",
        },
        {
            playerId: "24",
            team: null,
            adp: null,
            adr: null,
            name: "Matt Ryan",
            position: "QB",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "Bob",
        },
        {
            playerId: "2747",
            team: "SEA",
            adp: null,
            adr: null,
            name: "Jason Myers",
            position: "K",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "Bob",
        },
        {
            playerId: "3164",
            team: null,
            adp: 154.3,
            adr: 13,
            name: "Ezekiel Elliott",
            position: "RB",
            keeperValueForCurrentTeam: 2,
            diff: 11,
            rosteredBy: "Bob",
        },
        {
            playerId: "4037",
            team: "TB",
            adp: 55.7,
            adr: 5,
            name: "Chris Godwin",
            position: "WR",
            keeperValueForCurrentTeam: 6,
            diff: -1,
            rosteredBy: "Bob",
        },
        {
            playerId: "4080",
            team: "JAX",
            adp: 142,
            adr: 12,
            name: "Zay Jones",
            position: "WR",
            keeperValueForCurrentTeam: 13,
            diff: -1,
            rosteredBy: "Bob",
        },
        {
            playerId: "5248",
            team: "BAL",
            adp: 200,
            adr: 17,
            name: "Gus Edwards",
            position: "RB",
            keeperValueForCurrentTeam: 18,
            diff: -1,
            rosteredBy: "Bob",
        },
        {
            playerId: "5284",
            team: "MIA",
            adp: 174.7,
            adr: 15,
            name: "Jeff Wilson",
            position: "RB",
            keeperValueForCurrentTeam: 16,
            diff: -1,
            rosteredBy: "Bob",
        },
        {
            playerId: "6794",
            team: "MIN",
            adp: 1,
            adr: 1,
            name: "Justin Jefferson",
            position: "WR",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "Bob",
        },
        {
            playerId: "7527",
            team: "NE",
            adp: 188.3,
            adr: 16,
            name: "Mac Jones",
            position: "QB",
            keeperValueForCurrentTeam: 17,
            diff: -1,
            rosteredBy: "Bob",
        },
        {
            playerId: "7569",
            team: "HOU",
            adp: 149.7,
            adr: 13,
            name: "Nico Collins",
            position: "WR",
            keeperValueForCurrentTeam: 14,
            diff: -1,
            rosteredBy: "Bob",
        },
        {
            playerId: "7600",
            team: "PIT",
            adp: 101.7,
            adr: 9,
            name: "Pat Freiermuth",
            position: "TE",
            keeperValueForCurrentTeam: 8,
            diff: 1,
            rosteredBy: "Bob",
        },
        {
            playerId: "8132",
            team: "ATL",
            adp: 133.3,
            adr: 12,
            name: "Tyler Allgeier",
            position: "RB",
            keeperValueForCurrentTeam: 13,
            diff: -1,
            rosteredBy: "Bob",
        },
        {
            playerId: "8148",
            team: "DET",
            adp: 112,
            adr: 10,
            name: "Jameson Williams",
            position: "WR",
            keeperValueForCurrentTeam: 13,
            diff: -3,
            rosteredBy: "Bob",
        },
        {
            playerId: "NYJ",
            team: "NYJ",
            adp: 194.5,
            adr: 17,
            name: "NYJ DST",
            position: "DEF",
            keeperValueForCurrentTeam: 18,
            diff: -1,
            rosteredBy: "Bob",
        },
    ],
    6: [
        {
            playerId: "1110",
            team: null,
            adp: null,
            adr: null,
            name: "T.Y. Hilton",
            position: "WR",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "Hues",
        },
        {
            playerId: "2133",
            team: "LV",
            adp: 14.3,
            adr: 2,
            name: "Davante Adams",
            position: "WR",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "Hues",
        },
        {
            playerId: "2711",
            team: "ATL",
            adp: 282,
            adr: 24,
            name: "Taylor Heinicke",
            position: "QB",
            keeperValueForCurrentTeam: 18,
            diff: 6,
            rosteredBy: "Hues",
        },
        {
            playerId: "4033",
            team: "CLE",
            adp: 105.3,
            adr: 9,
            name: "David Njoku",
            position: "TE",
            keeperValueForCurrentTeam: 10,
            diff: -1,
            rosteredBy: "Hues",
        },
        {
            playerId: "4943",
            team: "SF",
            adp: 279.5,
            adr: 24,
            name: "Sam Darnold",
            position: "QB",
            keeperValueForCurrentTeam: 18,
            diff: 6,
            rosteredBy: "Hues",
        },
        {
            playerId: "4983",
            team: "CHI",
            adp: 51,
            adr: 5,
            name: "DJ Moore",
            position: "WR",
            keeperValueForCurrentTeam: 3,
            diff: 2,
            rosteredBy: "Hues",
        },
        {
            playerId: "5095",
            team: "LV",
            adp: null,
            adr: null,
            name: "Daniel Carlson",
            position: "K",
            keeperValueForCurrentTeam: 15,
            diff: 999,
            rosteredBy: "Hues",
        },
        {
            playerId: "5872",
            team: "SF",
            adp: 36.7,
            adr: 4,
            name: "Deebo Samuel",
            position: "WR",
            keeperValueForCurrentTeam: 7,
            diff: -3,
            rosteredBy: "Hues",
        },
        {
            playerId: "5892",
            team: "DET",
            adp: 78,
            adr: 7,
            name: "David Montgomery",
            position: "RB",
            keeperValueForCurrentTeam: 4,
            diff: 3,
            rosteredBy: "Hues",
        },
        {
            playerId: "5906",
            team: "BUF",
            adp: 172,
            adr: 15,
            name: "Dawson Knox",
            position: "TE",
            keeperValueForCurrentTeam: 16,
            diff: -1,
            rosteredBy: "Hues",
        },
        {
            playerId: "5967",
            team: "DAL",
            adp: 21.7,
            adr: 2,
            name: "Tony Pollard",
            position: "RB",
            keeperValueForCurrentTeam: 9,
            diff: -7,
            rosteredBy: "Hues",
        },
        {
            playerId: "6130",
            team: "HOU",
            adp: 146,
            adr: 13,
            name: "Devin Singletary",
            position: "RB",
            keeperValueForCurrentTeam: 9,
            diff: 4,
            rosteredBy: "Hues",
        },
        {
            playerId: "6801",
            team: "CIN",
            adp: 27.3,
            adr: 3,
            name: "Tee Higgins",
            position: "WR",
            keeperValueForCurrentTeam: 4,
            diff: -1,
            rosteredBy: "Hues",
        },
        {
            playerId: "6806",
            team: "BAL",
            adp: 54,
            adr: 5,
            name: "J.K. Dobbins",
            position: "RB",
            keeperValueForCurrentTeam: 6,
            diff: -1,
            rosteredBy: "Hues",
        },
        {
            playerId: "8137",
            team: "PIT",
            adp: 75,
            adr: 7,
            name: "George Pickens",
            position: "WR",
            keeperValueForCurrentTeam: 8,
            diff: -1,
            rosteredBy: "Hues",
        },
        {
            playerId: "96",
            team: "NYJ",
            adp: 108.3,
            adr: 10,
            name: "Aaron Rodgers",
            position: "QB",
            keeperValueForCurrentTeam: 4,
            diff: 6,
            rosteredBy: "Hues",
        },
        {
            playerId: "DAL",
            team: "DAL",
            adp: 161,
            adr: 14,
            name: "DAL DST",
            position: "DEF",
            keeperValueForCurrentTeam: 16,
            diff: -2,
            rosteredBy: "Hues",
        },
    ],
    7: [
        {
            playerId: "1166",
            team: "MIN",
            adp: 94,
            adr: 8,
            name: "Kirk Cousins",
            position: "QB",
            keeperValueForCurrentTeam: 6,
            diff: 2,
            rosteredBy: "Brayden",
        },
        {
            playerId: "1476",
            team: "BUF",
            adp: 266.3,
            adr: 23,
            name: "Latavius Murray",
            position: "RB",
            keeperValueForCurrentTeam: 18,
            diff: 5,
            rosteredBy: "Brayden",
        },
        {
            playerId: "3163",
            team: "DET",
            adp: 106.3,
            adr: 9,
            name: "Jared Goff",
            position: "QB",
            keeperValueForCurrentTeam: 10,
            diff: -1,
            rosteredBy: "Brayden",
        },
        {
            playerId: "4039",
            team: "LAR",
            adp: 5.3,
            adr: 1,
            name: "Cooper Kupp",
            position: "WR",
            keeperValueForCurrentTeam: 1,
            diff: 0,
            rosteredBy: "Brayden",
        },
        {
            playerId: "4040",
            team: "NE",
            adp: 108.3,
            adr: 10,
            name: "JuJu Smith-Schuster",
            position: "WR",
            keeperValueForCurrentTeam: 5,
            diff: 5,
            rosteredBy: "Brayden",
        },
        {
            playerId: "4098",
            team: null,
            adp: 173.3,
            adr: 15,
            name: "Kareem Hunt",
            position: "RB",
            keeperValueForCurrentTeam: 9,
            diff: 6,
            rosteredBy: "Brayden",
        },
        {
            playerId: "4195",
            team: "PHI",
            adp: null,
            adr: null,
            name: "Jake Elliott",
            position: "K",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "Brayden",
        },
        {
            playerId: "4217",
            team: "SF",
            adp: 59,
            adr: 5,
            name: "George Kittle",
            position: "TE",
            keeperValueForCurrentTeam: 4,
            diff: 1,
            rosteredBy: "Brayden",
        },
        {
            playerId: "4663",
            team: "LAC",
            adp: 5.3,
            adr: 1,
            name: "Austin Ekeler",
            position: "RB",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "Brayden",
        },
        {
            playerId: "4951",
            team: "CAR",
            adp: 175,
            adr: 15,
            name: "DJ Chark",
            position: "WR",
            keeperValueForCurrentTeam: 16,
            diff: -1,
            rosteredBy: "Brayden",
        },
        {
            playerId: "6790",
            team: "PHI",
            adp: 64.3,
            adr: 6,
            name: "D'Andre Swift",
            position: "RB",
            keeperValueForCurrentTeam: 1,
            diff: 5,
            rosteredBy: "Brayden",
        },
        {
            playerId: "6803",
            team: "SF",
            adp: 67.7,
            adr: 6,
            name: "Brandon Aiyuk",
            position: "WR",
            keeperValueForCurrentTeam: 8,
            diff: -2,
            rosteredBy: "Brayden",
        },
        {
            playerId: "6943",
            team: "BUF",
            adp: 90.7,
            adr: 8,
            name: "Gabe Davis",
            position: "WR",
            keeperValueForCurrentTeam: 7,
            diff: 1,
            rosteredBy: "Brayden",
        },
        {
            playerId: "7525",
            team: "PHI",
            adp: 24.7,
            adr: 3,
            name: "DeVonta Smith",
            position: "WR",
            keeperValueForCurrentTeam: 6,
            diff: -3,
            rosteredBy: "Brayden",
        },
        {
            playerId: "7526",
            team: "MIA",
            adp: 20.3,
            adr: 2,
            name: "Jaylen Waddle",
            position: "WR",
            keeperValueForCurrentTeam: 7,
            diff: -5,
            rosteredBy: "Brayden",
        },
        {
            playerId: "8122",
            team: "NYJ",
            adp: 281,
            adr: 24,
            name: "Zonovan Knight",
            position: "RB",
            keeperValueForCurrentTeam: 18,
            diff: 6,
            rosteredBy: "Brayden",
        },
        {
            playerId: "8135",
            team: "TEN",
            adp: 78,
            adr: 7,
            name: "Treylon Burks",
            position: "WR",
            keeperValueForCurrentTeam: 8,
            diff: -1,
            rosteredBy: "Brayden",
        },
        {
            playerId: "8159",
            team: "ATL",
            adp: 197.3,
            adr: 17,
            name: "Desmond Ridder",
            position: "QB",
            keeperValueForCurrentTeam: 18,
            diff: -1,
            rosteredBy: "Brayden",
        },
        {
            playerId: "DET",
            team: "DET",
            adp: 253,
            adr: 22,
            name: "DET DST",
            position: "DEF",
            keeperValueForCurrentTeam: 18,
            diff: 4,
            rosteredBy: "Brayden",
        },
    ],
    8: [
        {
            playerId: "1466",
            team: "KC",
            adp: 5.3,
            adr: 1,
            name: "Travis Kelce",
            position: "TE",
            keeperValueForCurrentTeam: 1,
            diff: 0,
            rosteredBy: "Jack",
        },
        {
            playerId: "2750",
            team: "LV",
            adp: null,
            adr: null,
            name: "DeAndre Carter",
            position: "WR",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "Jack",
        },
        {
            playerId: "3199",
            team: "NO",
            adp: 106,
            adr: 9,
            name: "Michael Thomas",
            position: "WR",
            keeperValueForCurrentTeam: 6,
            diff: 3,
            rosteredBy: "Jack",
        },
        {
            playerId: "3242",
            team: null,
            adp: null,
            adr: null,
            name: "Kenyan Drake",
            position: "RB",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "Jack",
        },
        {
            playerId: "3294",
            team: "DAL",
            adp: 83.7,
            adr: 7,
            name: "Dak Prescott",
            position: "QB",
            keeperValueForCurrentTeam: 3,
            diff: 4,
            rosteredBy: "Jack",
        },
        {
            playerId: "4950",
            team: "JAX",
            adp: 55.3,
            adr: 5,
            name: "Christian Kirk",
            position: "WR",
            keeperValueForCurrentTeam: 9,
            diff: -4,
            rosteredBy: "Jack",
        },
        {
            playerId: "5185",
            team: "NYJ",
            adp: 119.7,
            adr: 10,
            name: "Allen Lazard",
            position: "WR",
            keeperValueForCurrentTeam: 10,
            diff: 0,
            rosteredBy: "Jack",
        },
        {
            playerId: "5846",
            team: "SEA",
            adp: 32.7,
            adr: 3,
            name: "DK Metcalf",
            position: "WR",
            keeperValueForCurrentTeam: 5,
            diff: -2,
            rosteredBy: "Jack",
        },
        {
            playerId: "5927",
            team: "WAS",
            adp: 47.7,
            adr: 4,
            name: "Terry McLaurin",
            position: "WR",
            keeperValueForCurrentTeam: 2,
            diff: 2,
            rosteredBy: "Jack",
        },
        {
            playerId: "5947",
            team: "LV",
            adp: 128,
            adr: 11,
            name: "Jakobi Meyers",
            position: "WR",
            keeperValueForCurrentTeam: 13,
            diff: -2,
            rosteredBy: "Jack",
        },
        {
            playerId: "5955",
            team: "LV",
            adp: 196.7,
            adr: 17,
            name: "Hunter Renfrow",
            position: "WR",
            keeperValueForCurrentTeam: 11,
            diff: 6,
            rosteredBy: "Jack",
        },
        {
            playerId: "6650",
            team: "TB",
            adp: null,
            adr: null,
            name: "Chase McLaughlin",
            position: "K",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "Jack",
        },
        {
            playerId: "6813",
            team: "IND",
            adp: 12.7,
            adr: 2,
            name: "Jonathan Taylor",
            position: "RB",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "Jack",
        },
        {
            playerId: "7543",
            team: "JAX",
            adp: 35.3,
            adr: 3,
            name: "Travis Etienne",
            position: "RB",
            keeperValueForCurrentTeam: 4,
            diff: -1,
            rosteredBy: "Jack",
        },
        {
            playerId: "7561",
            team: "SF",
            adp: 125.3,
            adr: 11,
            name: "Elijah Mitchell",
            position: "RB",
            keeperValueForCurrentTeam: 5,
            diff: 6,
            rosteredBy: "Jack",
        },
        {
            playerId: "8142",
            team: "IND",
            adp: 166,
            adr: 14,
            name: "Alec Pierce",
            position: "WR",
            keeperValueForCurrentTeam: 17,
            diff: -3,
            rosteredBy: "Jack",
        },
        {
            playerId: "829",
            team: "CAR",
            adp: 323,
            adr: 27,
            name: "Andy Dalton",
            position: "QB",
            keeperValueForCurrentTeam: 18,
            diff: 9,
            rosteredBy: "Jack",
        },
        {
            playerId: "ARI",
            team: "ARI",
            adp: 300,
            adr: 25,
            name: "ARI DST",
            position: "DEF",
            keeperValueForCurrentTeam: 18,
            diff: 7,
            rosteredBy: "Jack",
        },
        {
            playerId: "SEA",
            team: "SEA",
            adp: 226,
            adr: 19,
            name: "SEA DST",
            position: "DEF",
            keeperValueForCurrentTeam: 18,
            diff: 1,
            rosteredBy: "Jack",
        },
    ],
    9: [
        {
            playerId: "1264",
            team: "BAL",
            adp: null,
            adr: null,
            name: "Justin Tucker",
            position: "K",
            keeperValueForCurrentTeam: 15,
            diff: 999,
            rosteredBy: "Quast",
        },
        {
            playerId: "2374",
            team: "SEA",
            adp: 68,
            adr: 6,
            name: "Tyler Lockett",
            position: "WR",
            keeperValueForCurrentTeam: 10,
            diff: -4,
            rosteredBy: "Quast",
        },
        {
            playerId: "2449",
            team: "BUF",
            adp: 10.3,
            adr: 1,
            name: "Stefon Diggs",
            position: "WR",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "Quast",
        },
        {
            playerId: "2749",
            team: "MIA",
            adp: 156.3,
            adr: 14,
            name: "Raheem Mostert",
            position: "RB",
            keeperValueForCurrentTeam: 15,
            diff: -1,
            rosteredBy: "Quast",
        },
        {
            playerId: "3225",
            team: "CIN",
            adp: 130.7,
            adr: 11,
            name: "Tyler Boyd",
            position: "WR",
            keeperValueForCurrentTeam: 12,
            diff: -1,
            rosteredBy: "Quast",
        },
        {
            playerId: "4017",
            team: "CLE",
            adp: 76.3,
            adr: 7,
            name: "Deshaun Watson",
            position: "QB",
            keeperValueForCurrentTeam: 17,
            diff: -10,
            rosteredBy: "Quast",
        },
        {
            playerId: "4149",
            team: "NO",
            adp: 107.7,
            adr: 9,
            name: "Jamaal Williams",
            position: "RB",
            keeperValueForCurrentTeam: 10,
            diff: -1,
            rosteredBy: "Quast",
        },
        {
            playerId: "4602",
            team: "CHI",
            adp: 308,
            adr: 26,
            name: "Robert Tonyan",
            position: "TE",
            keeperValueForCurrentTeam: 18,
            diff: 8,
            rosteredBy: "Quast",
        },
        {
            playerId: "4973",
            team: "CAR",
            adp: 192.7,
            adr: 17,
            name: "Hayden Hurst",
            position: "TE",
            keeperValueForCurrentTeam: 18,
            diff: -1,
            rosteredBy: "Quast",
        },
        {
            playerId: "4988",
            team: "CLE",
            adp: 16.3,
            adr: 2,
            name: "Nick Chubb",
            position: "RB",
            keeperValueForCurrentTeam: 1,
            diff: 1,
            rosteredBy: "Quast",
        },
        {
            playerId: "5848",
            team: "ARI",
            adp: 72.3,
            adr: 7,
            name: "Marquise Brown",
            position: "WR",
            keeperValueForCurrentTeam: 7,
            diff: 0,
            rosteredBy: "Quast",
        },
        {
            playerId: "5849",
            team: "ARI",
            adp: 155.3,
            adr: 13,
            name: "Kyler Murray",
            position: "QB",
            keeperValueForCurrentTeam: 3,
            diff: 10,
            rosteredBy: "Quast",
        },
        {
            playerId: "5850",
            team: "LV",
            adp: 20.3,
            adr: 2,
            name: "Josh Jacobs",
            position: "RB",
            keeperValueForCurrentTeam: 4,
            diff: -2,
            rosteredBy: "Quast",
        },
        {
            playerId: "6011",
            team: "IND",
            adp: 257,
            adr: 22,
            name: "Gardner Minshew",
            position: "QB",
            keeperValueForCurrentTeam: 18,
            diff: 4,
            rosteredBy: "Quast",
        },
        {
            playerId: "6824",
            team: "CLE",
            adp: 149.7,
            adr: 13,
            name: "Donovan Peoples-Jones",
            position: "WR",
            keeperValueForCurrentTeam: 14,
            diff: -1,
            rosteredBy: "Quast",
        },
        {
            playerId: "6904",
            team: "PHI",
            adp: 22.7,
            adr: 2,
            name: "Jalen Hurts",
            position: "QB",
            keeperValueForCurrentTeam: 4,
            diff: -2,
            rosteredBy: "Quast",
        },
        {
            playerId: "8172",
            team: "DEN",
            adp: 136.7,
            adr: 12,
            name: "Greg Dulcich",
            position: "TE",
            keeperValueForCurrentTeam: 13,
            diff: -1,
            rosteredBy: "Quast",
        },
        {
            playerId: "DEN",
            team: "DEN",
            adp: 210.5,
            adr: 18,
            name: "DEN DST",
            position: "DEF",
            keeperValueForCurrentTeam: 18,
            diff: 0,
            rosteredBy: "Quast",
        },
        {
            playerId: "TB",
            team: "TB",
            adp: 249,
            adr: 21,
            name: "TB DST",
            position: "DEF",
            keeperValueForCurrentTeam: 18,
            diff: 3,
            rosteredBy: "Quast",
        },
    ],
    10: [
        {
            playerId: "1049",
            team: "TEN",
            adp: 213,
            adr: 18,
            name: "Ryan Tannehill",
            position: "QB",
            keeperValueForCurrentTeam: 11,
            diff: 7,
            rosteredBy: "T Cool",
        },
        {
            playerId: "1689",
            team: "CAR",
            adp: 136,
            adr: 12,
            name: "Adam Thielen",
            position: "WR",
            keeperValueForCurrentTeam: 8,
            diff: 4,
            rosteredBy: "T Cool",
        },
        {
            playerId: "2161",
            team: "KC",
            adp: 130.3,
            adr: 11,
            name: "Jerick McKinnon",
            position: "RB",
            keeperValueForCurrentTeam: 12,
            diff: -1,
            rosteredBy: "T Cool",
        },
        {
            playerId: "3969",
            team: null,
            adp: 168.7,
            adr: 15,
            name: "Leonard Fournette",
            position: "RB",
            keeperValueForCurrentTeam: 5,
            diff: 10,
            rosteredBy: "T Cool",
        },
        {
            playerId: "4111",
            team: "CHI",
            adp: 143,
            adr: 12,
            name: "D'Onta Foreman",
            position: "RB",
            keeperValueForCurrentTeam: 13,
            diff: -1,
            rosteredBy: "T Cool",
        },
        {
            playerId: "4177",
            team: "ATL",
            adp: 277.3,
            adr: 24,
            name: "Mack Hollins",
            position: "WR",
            keeperValueForCurrentTeam: 18,
            diff: 6,
            rosteredBy: "T Cool",
        },
        {
            playerId: "4199",
            team: "GB",
            adp: 47,
            adr: 4,
            name: "Aaron Jones",
            position: "RB",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "T Cool",
        },
        {
            playerId: "4984",
            team: "BUF",
            adp: 21.3,
            adr: 2,
            name: "Josh Allen",
            position: "QB",
            keeperValueForCurrentTeam: 0,
            diff: 999,
            rosteredBy: "T Cool",
        },
        {
            playerId: "5844",
            team: "MIN",
            adp: 44,
            adr: 4,
            name: "T.J. Hockenson",
            position: "TE",
            keeperValueForCurrentTeam: 7,
            diff: -3,
            rosteredBy: "T Cool",
        },
        {
            playerId: "5859",
            team: "PHI",
            adp: 12.3,
            adr: 2,
            name: "A.J. Brown",
            position: "WR",
            keeperValueForCurrentTeam: 3,
            diff: -1,
            rosteredBy: "T Cool",
        },
        {
            playerId: "6149",
            team: "NYG",
            adp: 231.7,
            adr: 20,
            name: "Darius Slayton",
            position: "WR",
            keeperValueForCurrentTeam: 18,
            diff: 2,
            rosteredBy: "T Cool",
        },
        {
            playerId: "6768",
            team: "MIA",
            adp: 94.7,
            adr: 8,
            name: "Tua Tagovailoa",
            position: "QB",
            keeperValueForCurrentTeam: 5,
            diff: 3,
            rosteredBy: "T Cool",
        },
        {
            playerId: "6786",
            team: "DAL",
            adp: 11.7,
            adr: 1,
            name: "CeeDee Lamb",
            position: "WR",
            keeperValueForCurrentTeam: 1,
            diff: 0,
            rosteredBy: "T Cool",
        },
        {
            playerId: "6886",
            team: "CHI",
            adp: 208.7,
            adr: 18,
            name: "Chase Claypool",
            position: "WR",
            keeperValueForCurrentTeam: 18,
            diff: 0,
            rosteredBy: "T Cool",
        },
        {
            playerId: "6945",
            team: "WAS",
            adp: 99,
            adr: 9,
            name: "Antonio Gibson",
            position: "RB",
            keeperValueForCurrentTeam: 4,
            diff: 5,
            rosteredBy: "T Cool",
        },
        {
            playerId: "7839",
            team: "CIN",
            adp: null,
            adr: null,
            name: "Evan McPherson",
            position: "K",
            keeperValueForCurrentTeam: 18,
            diff: 999,
            rosteredBy: "T Cool",
        },
        {
            playerId: "BAL",
            team: "BAL",
            adp: 192.5,
            adr: 17,
            name: "BAL DST",
            position: "DEF",
            keeperValueForCurrentTeam: 16,
            diff: 1,
            rosteredBy: "T Cool",
        },
        {
            playerId: "NYG",
            team: "NYG",
            adp: 254,
            adr: 22,
            name: "NYG DST",
            position: "DEF",
            keeperValueForCurrentTeam: 18,
            diff: 4,
            rosteredBy: "T Cool",
        },
    ],
};
function App() {
    return <MobileApp data={data} />;
    return (
        <div className={styles.app}>
            <NavBar />
            <div className={styles.content}>
                {[
                    ...data[1],
                    ...data[2],
                    ...data[3],
                    ...data[4],
                    ...data[5],
                    ...data[6],
                    ...data[7],
                    ...data[8],
                    ...data[9],
                ].map((player) => {
                    return <PlayerCard {...player} />;
                })}
                {/* <Card keeperData={data} /> */}
            </div>
        </div>
    );
}

export default App;

//! Payout Ideas !\\
/*
- Payout Everytime you win
- Knockout Lowest Player Each Week
- 1st, 2nd, Most Points, 1st in Regular Season
- 3rd -> Money Back, 2nd -> 2x Money Back, 1st -> Rest, Weekly 1/3 Payout Hightst Score
-Payout for best QB RB WR TE K DEF
- 12 Teams, $150 Buy In, Champ gets $600 and tranactiob moneym SB loser gets $250
-10 team 100 buck buy in. Winner gets a G, 2nd gets money back, and last place kicks in an extra 100. 
*/

//! Keeper Rules !\\
/*
Our league format is a 3 keeper league, you franchise one player who is 🔒.
Then select 3 more from your roster (you can’t match position with franchise player) and they go into a lottery where 1 is randomly thrown back into the draft.
Can only keep players twice
- Undrafted Free Agents
We decided that they would go for an 8th round pick the first year and then jump 2 rounds every year afte
Our keeper league allows players to be kept in the round they were drafted and then increasing by 3 rounds each consecutive season up to their ADP. 
- no keepers in first 2 rounds
-trade still uses value- fibanacci for keepers
*/
