import { useState } from "react";
import reactLogo from "../assets/react.svg";
import viteLogo from "../../public/vite.svg";

import styles from "./Main.module.scss";
import Tab from "../components/Tab/Tab.jsx";
import SliderSelect from "../components/SliderSelect/SliderSelect";
import classNames from "classnames";
import _ from "lodash";

const getNumberSuffix = (number) => {
    const lastDigit = number % 10;

    if (lastDigit === 1) {
        return "st";
    } else if (lastDigit === 2) {
        return "nd";
    } else if (lastDigit === 3) {
        return "rd";
    } else {
        return "th";
    }

    return "";
};

const data = {
    "FanDuel Fan Boys": [
        {
            name: "Keenan Allen",
            value: 0,
            playerId: "1479",
            adr: 5,
            adp: 44.5,
            team: "LAC",
            position: "WR",
            id: "5f424505-f29f-433c-b3f2-1a143a04a010",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/15076.png",
            positionOrder: 3,
        },
        {
            name: "Tom Brady",
            value: 2,
            playerId: "167",
            adr: 9,
            adp: null,
            team: null,
            position: "QB",
            id: "41c44740-d0f6-44ab-8347-3b5d515e5ecf",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/4314.png",
            positionOrder: 1,
        },
        {
            name: "Dalvin Cook",
            value: 0,
            playerId: "4029",
            adr: 7,
            adp: 67.5,
            team: "MIN",
            position: "RB",
            id: "8960d61e-433b-41ea-a7ad-4e76be87b582",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18872.png",
            positionOrder: 2,
        },
        {
            name: "Christian McCaffrey",
            value: 0,
            playerId: "4034",
            adr: 1,
            adp: 3,
            team: "SF",
            position: "RB",
            id: "f96db0af-5e25-42d1-a07a-49b4e065b364",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18877.png",
            positionOrder: 2,
        },
        {
            name: "Gerald Everett",
            value: 18,
            playerId: "4089",
            isAdpCalculated: true,
            adr: 17,
            adp: 167,
            team: "LAC",
            position: "TE",
            id: "ebeceb00-57e0-4b74-9cf7-853da2afed18",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18935.png",
            positionOrder: 4,
        },
        {
            name: "James Conner",
            value: 1,
            playerId: "4137",
            adr: 9,
            adp: 83.5,
            team: "ARI",
            position: "RB",
            id: "28a084c0-14df-499f-bd1f-b975603626b7",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18983.png",
            positionOrder: 2,
        },
        {
            name: "Saquon Barkley",
            value: 0,
            playerId: "4866",
            adr: 2,
            adp: 15.5,
            team: "NYG",
            position: "RB",
            id: "9811b753-347c-467a-b3cb-85937e71e2b9",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19766.png",
            positionOrder: 2,
        },
        {
            name: "Dallas Goedert",
            value: 10,
            playerId: "5022",
            team: "PHI",
            position: "TE",
            id: "e8029983-87cf-49a2-bc04-04c8233a0630",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19863.png",
            positionOrder: 4,
        },
        {
            name: "Diontae Johnson",
            value: 3,
            playerId: "5937",
            adr: 8,
            adp: 75,
            team: "PIT",
            position: "WR",
            id: "244c00c7-fe9a-4f4f-adff-1d5b9c8877e7",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21077.png",
            positionOrder: 3,
        },
        {
            name: "Tyler Bass",
            value: 10,
            playerId: "7042",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "BUF",
            position: "K",
            id: "bfccbff4-bc01-41ed-aa11-be976160504c",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22108.png",
            positionOrder: 5,
        },
        {
            name: "Trevor Lawrence",
            value: 8,
            playerId: "7523",
            team: "JAX",
            position: "QB",
            id: "aaa8b42c-4d87-45f6-bfd2-e31cfed9a736",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22490.png",
            positionOrder: 1,
        },
        {
            name: "Javonte Williams",
            value: 2,
            playerId: "7588",
            team: "DEN",
            position: "RB",
            id: "889dcdc5-3d88-45df-9677-5ad7ff87c011",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22558.png",
            positionOrder: 2,
        },
        {
            name: "Rondale Moore",
            value: 18,
            playerId: "7601",
            isAdpCalculated: true,
            adr: 17,
            adp: 167,
            team: "ARI",
            position: "WR",
            id: "975555d0-fe82-4e88-90f4-d690f5000671",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22626.png",
            positionOrder: 3,
        },
        {
            name: "Drake London",
            value: 6,
            playerId: "8112",
            adr: 5,
            adp: 49,
            team: "ATL",
            position: "WR",
            id: "5053f9ae-15d9-4730-833d-484886b6f890",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23151.png",
            positionOrder: 3,
        },
        {
            name: "Rachaad White",
            value: 10,
            playerId: "8136",
            isAdpCalculated: true,
            adr: 9,
            adp: 80.5,
            team: "TB",
            position: "RB",
            id: "4d3f2f57-215c-4cb4-bf75-a7ecdcdded70",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23217.png",
            positionOrder: 2,
        },
        {
            name: "Kenny Pickett",
            value: 18,
            playerId: "8160",
            isAdpCalculated: true,
            adr: 17,
            adp: 168.5,
            team: "PIT",
            position: "QB",
            id: "ef7ae1f1-4ebe-4759-bbb3-32bd177ace08",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22501.png",
            positionOrder: 1,
        },
        {
            name: "Brock Purdy",
            value: 19,
            playerId: "8183",
            isAdpCalculated: true,
            adr: 20,
            adp: 193,
            team: "SF",
            position: "QB",
            id: "d5aef708-ad61-4ab8-a637-62ff96e92040",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23241.png",
            positionOrder: 1,
        },
        {
            name: "Isiah Pacheco",
            value: 9,
            playerId: "8205",
            isAdpCalculated: true,
            adr: 8,
            adp: 74.5,
            team: "KC",
            position: "RB",
            id: "3a25c037-fa30-4740-b742-ec8e4f1a2a25",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23371.png",
            positionOrder: 2,
        },
        {
            name: "San Francisco 49ers",
            value: 10,
            playerId: "SF",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "SF",
            position: "DEF",
            positionOrder: 6,
        },
    ],
    "Welcome to Olave Garden": [
        {
            name: "Dare Ogunbowale",
            value: 10,
            playerId: "4718",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "HOU",
            position: "RB",
            id: "42b57148-fc06-4aee-b40b-bb941271b5b7",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19626.png",
            positionOrder: 2,
        },
        {
            name: "Lamar Jackson",
            value: 2,
            playerId: "4881",
            adr: 4,
            adp: 31.5,
            team: "BAL",
            position: "QB",
            id: "e06a9c07-453a-4bb0-a7e9-2c3a64166dad",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19781.png",
            positionOrder: 1,
        },
        {
            name: "Mark Andrews",
            value: 2,
            playerId: "5012",
            team: "BAL",
            position: "TE",
            id: "0618f387-9b72-4270-8b8f-dec4cccc9e4a",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19803.png",
            positionOrder: 4,
        },
        {
            name: "Michael Badgley",
            value: 10,
            playerId: "5230",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "DET",
            position: "K",
            id: "375b0d7f-8d03-4111-8c1b-62907f0326a1",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20144.png",
            positionOrder: 5,
        },
        {
            name: "Parris Campbell",
            value: 19,
            playerId: "5880",
            isAdpCalculated: true,
            adr: 22,
            adp: 217.5,
            team: "NYG",
            position: "WR",
            id: "db0c3b1c-8d18-435a-864a-cdd696f963b6",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21005.png",
            positionOrder: 3,
        },
        {
            name: "Damien Harris",
            value: 13,
            playerId: "5890",
            isAdpCalculated: true,
            adr: 12,
            adp: 114,
            team: "BUF",
            position: "RB",
            id: "59482736-ce42-4058-b68e-0f9f66eac2d9",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20790.png",
            positionOrder: 2,
        },
        {
            name: "Jerry Jeudy",
            value: 6,
            playerId: "6783",
            adr: 5,
            adp: 46.5,
            team: "DEN",
            position: "WR",
            id: "eaaa4a61-c2a7-4926-8e9b-3ec71be2f991",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21692.png",
            positionOrder: 3,
        },
        {
            name: "Justin Herbert",
            value: 0,
            playerId: "6797",
            adr: 6,
            adp: 54,
            team: "LAC",
            position: "QB",
            id: "f0a8f8e3-b9e9-46ed-85e4-eec6452a8a44",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21681.png",
            positionOrder: 1,
        },
        {
            name: "A.J. Dillon",
            value: 8,
            playerId: "6828",
            adr: 12,
            adp: 110.5,
            team: "GB",
            position: "RB",
            id: "e10bfeb8-ea01-47bc-bfa8-45f6dcbf71b3",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21802.png",
            positionOrder: 2,
        },
        {
            name: "Tony Jones",
            value: 10,
            playerId: "6984",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "DEN",
            position: "RB",
            id: "83d4c4c3-3c40-49b1-8b86-25d256a0b5ad",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21774.png",
            positionOrder: 2,
        },
        {
            name: "Tyler Huntley",
            value: 19,
            playerId: "7083",
            isAdpCalculated: true,
            adr: 37,
            adp: 363,
            team: "BAL",
            position: "QB",
            id: "7c226f73-a59f-4db6-ad98-2766d05d4d5a",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21810.png",
            positionOrder: 1,
        },
        {
            name: "Najee Harris",
            value: 0,
            playerId: "7528",
            adr: 4,
            adp: 39,
            team: "PIT",
            position: "RB",
            id: "48ec58c3-ec26-4434-b005-8d34035e6667",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21768.png",
            positionOrder: 2,
        },
        {
            name: "Ja'Marr Chase",
            value: 0,
            playerId: "7564",
            adr: 1,
            adp: 2,
            team: "CIN",
            position: "WR",
            id: "fa99e984-d63b-4ef4-a164-407f68a7eeaf",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22564.png",
            positionOrder: 3,
        },
        {
            name: "Rhamondre Stevenson",
            value: 0,
            playerId: "7611",
            adr: 3,
            adp: 28.5,
            team: "NE",
            position: "RB",
            id: "6260e78a-64e2-4f7e-9bf8-39948a17a370",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22546.png",
            positionOrder: 2,
        },
        {
            name: "Dameon Pierce",
            value: 6,
            playerId: "8129",
            adr: 7,
            adp: 63.5,
            team: "HOU",
            position: "RB",
            id: "5d4ef6da-a6b5-4d9c-adc0-28dfdbe9315e",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23223.png",
            positionOrder: 2,
        },
        {
            name: "Chris Olave",
            value: 7,
            playerId: "8144",
            team: "NO",
            position: "WR",
            id: "2375d572-a36c-4365-bb3f-87e156526e2f",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22565.png",
            positionOrder: 3,
        },
        {
            name: "Buffalo Bills",
            value: 14,
            playerId: "BUF",
            team: "BUF",
            position: "DEF",
            positionOrder: 6,
        },
        {
            name: "New England Patriots",
            value: 10,
            playerId: "NE",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "NE",
            position: "DEF",
            positionOrder: 6,
        },
    ],
    "Unleash the K9": [
        {
            name: "Amari Cooper",
            value: 5,
            playerId: "2309",
            adr: 4,
            adp: 37,
            team: "CLE",
            position: "WR",
            id: "00f88be8-45f9-4237-b2b8-3271ec790d07",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/16765.png",
            positionOrder: 3,
        },
        {
            name: "Tyreek Hill",
            value: 0,
            playerId: "3321",
            adr: 1,
            adp: 5,
            team: "MIA",
            position: "WR",
            id: "01d8aee3-e1c4-4988-970a-8c0c2d08bd83",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18082.png",
            positionOrder: 3,
        },
        {
            name: "Joe Mixon",
            value: 0,
            playerId: "4018",
            adr: 7,
            adp: 61.5,
            team: "CIN",
            position: "RB",
            id: "7797f36e-87e8-4282-b6d2-bdb1774fc3b3",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18858.png",
            positionOrder: 2,
        },
        {
            name: "Patrick Mahomes",
            value: 1,
            playerId: "4046",
            team: "KC",
            position: "QB",
            id: "11cad59d-90dd-449c-a839-dddaba4fe16c",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18890.png",
            positionOrder: 1,
        },
        {
            name: "Curtis Samuel",
            value: 19,
            playerId: "4082",
            isAdpCalculated: true,
            adr: 19,
            adp: 182.5,
            team: "WAS",
            position: "WR",
            id: "66a21b6d-97e5-4732-8bb0-062145d6bbc6",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18928.png",
            positionOrder: 3,
        },
        {
            name: "Samaje Perine",
            value: 12,
            playerId: "4147",
            isAdpCalculated: true,
            adr: 11,
            adp: 108.5,
            team: "DEN",
            position: "RB",
            id: "e601812f-ce24-4e99-bee0-e33c1e9014e4",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18993.png",
            positionOrder: 2,
        },
        {
            name: "Baker Mayfield",
            value: 19,
            playerId: "4892",
            isAdpCalculated: true,
            adr: 23,
            adp: 221.5,
            team: "TB",
            position: "QB",
            id: "30198d30-9769-4e10-ac86-b4c91d940802",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19790.png",
            positionOrder: 1,
        },
        {
            name: "Dalton Schultz",
            value: 4,
            playerId: "5001",
            adr: 13,
            adp: 124,
            team: "HOU",
            position: "TE",
            id: "8caec1b4-e0b6-4a84-b8c8-617d6e91ef6a",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19920.png",
            positionOrder: 4,
        },
        {
            name: "Michael Gallup",
            value: 14,
            playerId: "5038",
            team: "DAL",
            position: "WR",
            id: "9e174ff2-ca0e-4e6b-96f7-90f0088f7edd",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19867.png",
            positionOrder: 3,
        },
        {
            name: "Mike White",
            value: 19,
            playerId: "5089",
            isAdpCalculated: true,
            adr: 27,
            adp: 267,
            team: "MIA",
            position: "QB",
            id: "f4808328-86e9-459d-a2bc-18e90c7d211e",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19972.png",
            positionOrder: 1,
        },
        {
            name: "Nick Folk",
            value: 10,
            playerId: "650",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "NE",
            position: "K",
            id: "b37c621e-1125-4c35-bea0-fcabb1527060",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/11694.png",
            positionOrder: 5,
        },
        {
            name: "Cole Kmet",
            value: 15,
            playerId: "6826",
            isAdpCalculated: true,
            adr: 14,
            adp: 135.5,
            team: "CHI",
            position: "TE",
            id: "036feeb6-9a22-43c5-a8e3-7ac611d8ff49",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21772.png",
            positionOrder: 4,
        },
        {
            name: "James Robinson",
            value: 14,
            playerId: "6955",
            adr: 23,
            adp: 220.5,
            team: "NE",
            position: "RB",
            id: "5fc196a1-2015-49c7-85b2-1adbd2c33cf5",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21970.png",
            positionOrder: 2,
        },
        {
            name: "Zach Wilson",
            value: 19,
            playerId: "7538",
            isAdpCalculated: true,
            adr: 36,
            adp: 351,
            team: "NYJ",
            position: "QB",
            id: "17bb63b1-1b0e-48e1-baf7-55cd314d0e62",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22495.png",
            positionOrder: 1,
        },
        {
            name: "Amon-Ra St. Brown",
            value: 4,
            playerId: "7547",
            adr: 2,
            adp: 13.5,
            team: "DET",
            position: "WR",
            id: "26ef0447-29b8-4dd1-9831-dcbf8132bb74",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22587.png",
            positionOrder: 3,
        },
        {
            name: "Garrett Wilson",
            value: 7,
            playerId: "8146",
            team: "NYJ",
            position: "WR",
            id: "68d72fe0-79b2-4fdb-afd5-6c79676e77f3",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23122.png",
            positionOrder: 3,
        },
        {
            name: "Kenneth Walker",
            value: 5,
            playerId: "8151",
            adr: 5,
            adp: 46,
            team: "SEA",
            position: "RB",
            id: "22ee9bac-a64c-4d44-94fc-51d775465b3b",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23214.png",
            positionOrder: 2,
        },
        {
            name: "Philadelphia Eagles",
            value: 10,
            playerId: "PHI",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "PHI",
            position: "DEF",
            positionOrder: 6,
        },
    ],
    "We aint write back tho  ": [
        {
            name: "Geno Smith",
            value: 13,
            playerId: "1373",
            isAdpCalculated: true,
            adr: 12,
            adp: 113.5,
            team: "SEA",
            position: "QB",
            id: "cfc93f5e-105e-4a5e-88d3-f4279893cfa8",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/14895.png",
            positionOrder: 1,
        },
        {
            name: "Mike Evans",
            value: 1,
            playerId: "2216",
            team: "TB",
            position: "WR",
            id: "c48c21d9-0ae5-478c-ad34-30a660cfa9b8",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/16597.png",
            positionOrder: 3,
        },
        {
            name: "Darren Waller",
            value: 3,
            playerId: "2505",
            team: "NYG",
            position: "TE",
            id: "14c97c9f-26e8-4944-9299-f90de6aeada3",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/16964.png",
            positionOrder: 4,
        },
        {
            name: "Derrick Henry",
            value: 0,
            playerId: "3198",
            adr: 3,
            adp: 27,
            team: "TEN",
            position: "RB",
            id: "87c481c7-7414-43cc-82df-19ca0c2ae22e",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/17959.png",
            positionOrder: 2,
        },
        {
            name: "Alvin Kamara",
            value: 0,
            playerId: "4035",
            adr: 10,
            adp: 99.5,
            team: "NO",
            position: "RB",
            id: "d9c857b2-97da-4fb8-a527-afbbb2a67413",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18878.png",
            positionOrder: 2,
        },
        {
            name: "Mike Williams",
            value: 6,
            playerId: "4068",
            adr: 5,
            adp: 46,
            team: "LAC",
            position: "WR",
            id: "12f27311-7cd6-4ca5-ba7d-571e9de5e1eb",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18914.png",
            positionOrder: 3,
        },
        {
            name: "Harrison Butker",
            value: 10,
            playerId: "4227",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "KC",
            position: "K",
            id: "4ceb866c-8eaf-49b5-9043-56228e43a2e5",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19073.png",
            positionOrder: 5,
        },
        {
            name: "Courtland Sutton",
            value: 4,
            playerId: "5045",
            team: "DEN",
            position: "WR",
            id: "b55ae5ba-593f-4560-9cab-14e10698e01d",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19800.png",
            positionOrder: 3,
        },
        {
            name: "Daniel Jones",
            value: 12,
            playerId: "5870",
            adr: 10,
            adp: 97.5,
            team: "NYG",
            position: "QB",
            id: "0042266b-cb28-4012-bfd2-06650badad97",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20841.png",
            positionOrder: 1,
        },
        {
            name: "Foster Moreau",
            value: 19,
            playerId: "5985",
            isAdpCalculated: true,
            adr: 25,
            adp: 249.5,
            team: "NO",
            position: "TE",
            id: "9c3a67fd-5c6e-4689-9e08-9ff6d4db6c9a",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20884.png",
            positionOrder: 4,
        },
        {
            name: "Miles Sanders",
            value: 8,
            playerId: "6151",
            team: "CAR",
            position: "RB",
            id: "ef3ceaf4-b733-4e06-a7f4-a94fc67361c1",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20933.png",
            positionOrder: 2,
        },
        {
            name: "Joe Burrow",
            value: 2,
            playerId: "6770",
            team: "CIN",
            position: "QB",
            id: "3023ac10-4e7f-425f-9fc5-2b8e6332c92e",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21693.png",
            positionOrder: 1,
        },
        {
            name: "Michael Pittman",
            value: 5,
            playerId: "6819",
            team: "IND",
            position: "WR",
            id: "1aefd5e2-1f85-471a-91a5-4aad4cf6fe6d",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21744.png",
            positionOrder: 3,
        },
        {
            name: "Justin Fields",
            value: 5,
            playerId: "7591",
            team: "CHI",
            position: "QB",
            id: "cf15be8f-9117-4531-a517-2b9c7cb3e9e1",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22492.png",
            positionOrder: 1,
        },
        {
            name: "Khalil Herbert",
            value: 16,
            playerId: "7608",
            team: "CHI",
            position: "RB",
            id: "02af99e0-3c84-4d4e-937a-a9f29a02323b",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22563.png",
            positionOrder: 2,
        },
        {
            name: "Brian Robinson",
            value: 10,
            playerId: "8154",
            team: "WAS",
            position: "RB",
            id: "795f636e-6f7f-4bc7-a346-2862272abead",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23190.png",
            positionOrder: 2,
        },
        {
            name: "Christian Watson",
            value: 6,
            playerId: "8167",
            isAdpCalculated: true,
            adr: 5,
            adp: 42.5,
            team: "GB",
            position: "WR",
            id: "47d97f44-b4aa-46d2-816c-5b5a1fe48d46",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23395.png",
            positionOrder: 3,
        },
        {
            name: "Miami Dolphins",
            value: 10,
            playerId: "MIA",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "MIA",
            position: "DEF",
            positionOrder: 6,
        },
        {
            name: "Washington Football Team",
            value: 10,
            playerId: "WAS",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "WAS",
            position: "DEF",
            positionOrder: 6,
        },
    ],
    "Mooney Toons": [
        {
            name: "Russell Wilson",
            value: 2,
            playerId: "1234",
            adr: 13,
            adp: 127.5,
            team: "DEN",
            position: "QB",
            id: "409d4cac-ee90-4470-9710-ebe671678339",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/14536.png",
            positionOrder: 1,
        },
        {
            name: "DeAndre Hopkins",
            value: 0,
            playerId: "1426",
            adr: 5,
            adp: 42.5,
            team: "ARI",
            position: "WR",
            id: "5c48ade7-4b9a-4757-9643-87a6e3839e2b",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/14986.png",
            positionOrder: 3,
        },
        {
            name: "Cordarrelle Patterson",
            value: 8,
            playerId: "1535",
            team: "ATL",
            position: "RB",
            id: "da85107c-365c-4d58-90ab-479d97d798b4",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/15150.png",
            positionOrder: 2,
        },
        {
            name: "Derek Carr",
            value: 3,
            playerId: "2028",
            team: "NO",
            position: "QB",
            id: "9f026fc0-4449-4dc5-a226-2e2830619381",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/16311.png",
            positionOrder: 1,
        },
        {
            name: "Matt Ryan",
            value: 10,
            playerId: "24",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: null,
            position: "QB",
            id: "7e648a0b-fdc8-4661-a587-5826f2cac11b",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/732.png",
            positionOrder: 1,
        },
        {
            name: "Jason Myers",
            value: 10,
            playerId: "2747",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "SEA",
            position: "K",
            id: "7af4c94b-529b-4403-ab66-2bfed3fcf0c7",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/17215.png",
            positionOrder: 5,
        },
        {
            name: "Ezekiel Elliott",
            value: 1,
            playerId: "3164",
            adr: 9,
            adp: null,
            team: null,
            position: "RB",
            id: "bef8b2b4-78bd-4a4d-bb5d-6b55ada9ef6a",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/17923.png",
            positionOrder: 2,
        },
        {
            name: "Chris Godwin",
            value: 5,
            playerId: "4037",
            adr: 6,
            adp: 56,
            team: "TB",
            position: "WR",
            id: "baa61bb5-f8d0-4f90-bbe2-028576b8d33d",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18880.png",
            positionOrder: 3,
        },
        {
            name: "Zay Jones",
            value: 14,
            playerId: "4080",
            isAdpCalculated: true,
            adr: 13,
            adp: 123.5,
            team: "JAX",
            position: "WR",
            id: "a28f7368-0306-4d20-855f-285a1a09c09c",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18926.png",
            positionOrder: 3,
        },
        {
            name: "Gus Edwards",
            value: 19,
            playerId: "5248",
            isAdpCalculated: true,
            adr: 21,
            adp: 202,
            team: "BAL",
            position: "RB",
            id: "3ffc3993-461e-4477-9def-c9633b7feac1",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20239.png",
            positionOrder: 2,
        },
        {
            name: "Jeff Wilson",
            value: 15,
            playerId: "5284",
            isAdpCalculated: true,
            adr: 17,
            adp: 168,
            team: "MIA",
            position: "RB",
            id: "72cf3127-3953-4fd8-8049-3de1b6fa9825",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20360.png",
            positionOrder: 2,
        },
        {
            name: "Justin Jefferson",
            value: 0,
            playerId: "6794",
            adr: 1,
            adp: 1,
            team: "MIN",
            position: "WR",
            id: "4131d4ee-0318-4bb5-832a-4dec80668a4f",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21685.png",
            positionOrder: 3,
        },
        {
            name: "Mac Jones",
            value: 19,
            playerId: "7527",
            isAdpCalculated: true,
            adr: 21,
            adp: 205.5,
            team: "NE",
            position: "QB",
            id: "1fd00ec3-b758-46d2-a2c1-cca521ea8a54",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22496.png",
            positionOrder: 1,
        },
        {
            name: "Nico Collins",
            value: 16,
            playerId: "7569",
            isAdpCalculated: true,
            adr: 15,
            adp: 142.5,
            team: "HOU",
            position: "WR",
            id: "bd56a50c-5fae-4ee2-8363-f74ae07b6887",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21756.png",
            positionOrder: 3,
        },
        {
            name: "Pat Freiermuth",
            value: 7,
            playerId: "7600",
            team: "PIT",
            position: "TE",
            id: "04f0fefe-9d9d-44f5-94ea-6df2a42df3c6",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22507.png",
            positionOrder: 4,
        },
        {
            name: "Tyler Allgeier",
            value: 16,
            playerId: "8132",
            isAdpCalculated: true,
            adr: 15,
            adp: 146.5,
            team: "ATL",
            position: "RB",
            id: "f4529909-1a02-4f4b-a1f3-315cad100683",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23250.png",
            positionOrder: 2,
        },
        {
            name: "Jameson Williams",
            value: 12,
            playerId: "8148",
            team: "DET",
            position: "WR",
            id: "590adb00-5598-47ad-b6d4-16a6c5519847",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23234.png",
            positionOrder: 3,
        },
        {
            name: "New York Jets",
            value: 10,
            playerId: "NYJ",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "NYJ",
            position: "DEF",
            positionOrder: 6,
        },
    ],
    "Davante’s Inferno": [
        {
            name: "T.Y. Hilton",
            value: 10,
            playerId: "1110",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: null,
            position: "WR",
            id: "b8426cea-f8b9-4061-8d56-e70d1230103e",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/14005.png",
            positionOrder: 3,
        },
        {
            name: "Davante Adams",
            value: 0,
            playerId: "2133",
            adr: 2,
            adp: 10.5,
            team: "LV",
            position: "WR",
            id: "e7d6ae25-bf15-4660-8b37-c37716551de3",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/16470.png",
            positionOrder: 3,
        },
        {
            name: "Taylor Heinicke",
            value: 19,
            playerId: "2711",
            isAdpCalculated: true,
            adr: 36,
            adp: 358,
            team: "ATL",
            position: "QB",
            id: "2c259733-ec2c-4e3c-bb7b-34dc0d37dc34",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/17179.png",
            positionOrder: 1,
        },
        {
            name: "David Njoku",
            value: 12,
            playerId: "4033",
            isAdpCalculated: true,
            adr: 11,
            adp: 101.5,
            team: "CLE",
            position: "TE",
            id: "8f86fcea-90e8-49ea-bc78-5c7659313e57",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18876.png",
            positionOrder: 4,
        },
        {
            name: "Sam Darnold",
            value: 19,
            playerId: "4943",
            isAdpCalculated: true,
            adr: 26,
            adp: 258,
            team: "SF",
            position: "QB",
            id: "13d826c5-9b22-4e0a-a877-02d8c84c546b",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19812.png",
            positionOrder: 1,
        },
        {
            name: "D.J. Moore",
            value: 3,
            playerId: "4983",
            adr: 5,
            adp: 44.5,
            team: "CHI",
            position: "WR",
            id: "d8202e6d-d03b-4cd1-a793-ff8fd39d9755",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19844.png",
            positionOrder: 3,
        },
        {
            name: "Daniel Carlson",
            value: 14,
            playerId: "5095",
            team: "LV",
            position: "K",
            id: "7bb70550-c28a-4e47-9a13-cc0c0fef8b38",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19989.png",
            positionOrder: 5,
        },
        {
            name: "Deebo Samuel",
            value: 5,
            playerId: "5872",
            team: "SF",
            position: "WR",
            id: "628a6a0a-4fde-4024-8d7c-28674953d5af",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20932.png",
            positionOrder: 3,
        },
        {
            name: "David Montgomery",
            value: 3,
            playerId: "5892",
            adr: 9,
            adp: 80.5,
            team: "DET",
            position: "RB",
            id: "1c9e1cd5-8cb1-4a15-a2c8-3a0c0fd5423c",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20882.png",
            positionOrder: 2,
        },
        {
            name: "Dawson Knox",
            value: 17,
            playerId: "5906",
            isAdpCalculated: true,
            adr: 16,
            adp: 159,
            team: "BUF",
            position: "TE",
            id: "5fb525c5-4e70-4ede-8c49-94ad0cf66b7d",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20850.png",
            positionOrder: 4,
        },
        {
            name: "Tony Pollard",
            value: 8,
            playerId: "5967",
            adr: 3,
            adp: 21.5,
            team: "DAL",
            position: "RB",
            id: "33b0227d-4c21-4e71-b4cd-be35f7db9123",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20912.png",
            positionOrder: 2,
        },
        {
            name: "Devin Singletary",
            value: 8,
            playerId: "6130",
            team: "HOU",
            position: "RB",
            id: "a961b0d4-5d7c-438e-90f0-2e1fa09f6c89",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20941.png",
            positionOrder: 2,
        },
        {
            name: "Tee Higgins",
            value: 2,
            playerId: "6801",
            team: "CIN",
            position: "WR",
            id: "7963b029-5de4-4541-b00a-44eefe4349af",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21690.png",
            positionOrder: 3,
        },
        {
            name: "J.K. Dobbins",
            value: 7,
            playerId: "6806",
            isAdpCalculated: true,
            adr: 6,
            adp: 57,
            team: "BAL",
            position: "RB",
            id: "a57b9914-4315-4295-98b4-9b348c52d6a1",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21674.png",
            positionOrder: 2,
        },
        {
            name: "George Pickens",
            value: 9,
            playerId: "8137",
            isAdpCalculated: true,
            adr: 8,
            adp: 72.5,
            team: "PIT",
            position: "WR",
            id: "018e8f25-54e5-44f1-967a-7ff237f1c52f",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23153.png",
            positionOrder: 3,
        },
        {
            name: "Aaron Rodgers",
            value: 3,
            playerId: "96",
            team: "NYJ",
            position: "QB",
            id: "0ce48193-e2fa-466e-a986-33f751add206",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/2593.png",
            positionOrder: 1,
        },
        {
            name: "Dallas Cowboys",
            value: 14,
            playerId: "DAL",
            adr: 9,
            adp: null,
            team: "DAL",
            position: "DEF",
            positionOrder: 6,
        },
    ],
    "Kittles n bits ": [
        {
            name: "Kirk Cousins",
            value: 5,
            playerId: "1166",
            team: "MIN",
            position: "QB",
            id: "bbd0942c-6f77-4f83-a6d0-66ec6548019e",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/14252.png",
            positionOrder: 1,
        },
        {
            name: "Latavius Murray",
            value: 19,
            playerId: "1476",
            isAdpCalculated: true,
            adr: 25,
            adp: 245.5,
            team: "BUF",
            position: "RB",
            id: "540f8b30-900e-4d17-8756-c262ba5fa039",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/15071.png",
            positionOrder: 2,
        },
        {
            name: "Jared Goff",
            value: 10,
            playerId: "3163",
            isAdpCalculated: true,
            adr: 12,
            adp: 117,
            team: "DET",
            position: "QB",
            id: "aba8f925-ffbf-4654-bfa7-a25d3d237494",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/17922.png",
            positionOrder: 1,
        },
        {
            name: "Cooper Kupp",
            value: 0,
            playerId: "4039",
            adr: 1,
            adp: 5,
            team: "LAR",
            position: "WR",
            id: "2806e915-c46f-492f-8a29-71d3a85e5620",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18882.png",
            positionOrder: 3,
        },
        {
            name: "JuJu Smith-Schuster",
            value: 4,
            playerId: "4040",
            team: "NE",
            position: "WR",
            id: "9547fbb1-0d4f-4d9e-83b9-e2fa30463bb9",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18883.png",
            positionOrder: 3,
        },
        {
            name: "Kareem Hunt",
            value: 1,
            playerId: "4098",
            team: null,
            position: "RB",
            id: "0ef0d0ca-2d2d-455b-ab63-a20c01303e37",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18944.png",
            positionOrder: 2,
        },
        {
            name: "Jake Elliott",
            value: 10,
            playerId: "4195",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "PHI",
            position: "K",
            id: "059e5bb7-1842-4558-9aaf-77c352a21216",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19041.png",
            positionOrder: 5,
        },
        {
            name: "George Kittle",
            value: 3,
            playerId: "4217",
            team: "SF",
            position: "TE",
            id: "2ada91b0-036e-454f-83c3-6d939ff584a9",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19063.png",
            positionOrder: 4,
        },
        {
            name: "Austin Ekeler",
            value: 0,
            playerId: "4663",
            adr: 1,
            adp: 10,
            team: "LAC",
            position: "RB",
            id: "e5b8c439-a48a-4f83-b63b-1a4d30e04cd3",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19562.png",
            positionOrder: 2,
        },
        {
            name: "DJ Chark Jr.",
            value: 16,
            playerId: "4951",
            isAdpCalculated: true,
            adr: 15,
            adp: 147,
            team: "CAR",
            position: "WR",
            id: "c2a7bd8a-d141-423a-8810-0988a59ff0b4",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19816.png",
            positionOrder: 3,
        },
        {
            name: "D'Andre Swift",
            value: 0,
            playerId: "6790",
            adr: 7,
            adp: 70,
            team: "PHI",
            position: "RB",
            id: "cc4b5f58-a11c-4450-a1df-617ad88336e4",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21684.png",
            positionOrder: 2,
        },
        {
            name: "Brandon Aiyuk",
            value: 7,
            playerId: "6803",
            adr: 7,
            adp: 63.5,
            team: "SF",
            position: "WR",
            id: "c90471cc-fa60-4416-9388-5aebb5d877eb",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21747.png",
            positionOrder: 3,
        },
        {
            name: "Gabe Davis",
            value: 5,
            playerId: "6943",
            adr: 8,
            adp: 79.5,
            team: "BUF",
            position: "WR",
            id: "dc397432-7157-4ce4-976d-b9662cc6f551",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21735.png",
            positionOrder: 3,
        },
        {
            name: "DeVonta Smith",
            value: 6,
            playerId: "7525",
            adr: 3,
            adp: 23,
            team: "PHI",
            position: "WR",
            id: "3555d07e-57ae-43de-97d5-b1b5bf055f17",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21687.png",
            positionOrder: 3,
        },
        {
            name: "Jaylen Waddle",
            value: 5,
            playerId: "7526",
            team: "MIA",
            position: "WR",
            id: "0ff9a975-669d-4851-a95d-ab28d9fc29c4",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22598.png",
            positionOrder: 3,
        },
        {
            name: "Zonovan Knight",
            value: null,
            playerId: "8122",
            adr: 29,
            adp: 288.5,
            team: "NYJ",
            position: "RB",
            id: "53df5e30-d3bd-11ec-96a0-c3471a31202c",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23847.png",
            positionOrder: 2,
        },
        {
            name: "Treylon Burks",
            value: 9,
            playerId: "8135",
            isAdpCalculated: true,
            adr: 8,
            adp: 76,
            team: "TEN",
            position: "WR",
            id: "45763342-0208-46ab-a5d2-6c6e4ff66b66",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23119.png",
            positionOrder: 3,
        },
        {
            name: "Desmond Ridder",
            value: 19,
            playerId: "8159",
            isAdpCalculated: true,
            adr: 21,
            adp: 202.5,
            team: "ATL",
            position: "QB",
            id: "6bf35760-217c-401d-b80b-2ae7cc5d7564",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22502.png",
            positionOrder: 1,
        },
        {
            name: "Detroit Lions",
            value: 10,
            playerId: "DET",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "DET",
            position: "DEF",
            positionOrder: 6,
        },
    ],
    "January 6th Dust-Ups": [
        {
            name: "Travis Kelce",
            value: 0,
            playerId: "1466",
            adr: 1,
            adp: 5,
            team: "KC",
            position: "TE",
            id: "c3859e06-5f23-4302-a71b-04820a899d5f",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/15048.png",
            positionOrder: 4,
        },
        {
            name: "DeAndre Carter",
            value: 19,
            playerId: "2750",
            isAdpCalculated: true,
            adr: 35,
            adp: 344,
            team: "LV",
            position: "WR",
            id: "9ae2584a-40c1-4b30-be34-a9567659eacd",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/17218.png",
            positionOrder: 3,
        },
        {
            name: "Michael Thomas",
            value: 4,
            playerId: "3199",
            team: "NO",
            position: "WR",
            id: "90c1756d-1f47-41b7-89fe-b113c9850bc1",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/17960.png",
            positionOrder: 3,
        },
        {
            name: "Kenyan Drake",
            value: 10,
            playerId: "3242",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: null,
            position: "RB",
            id: "a0b93053-d349-4dd1-a840-24577102699b",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18003.png",
            positionOrder: 2,
        },
        {
            name: "Dak Prescott",
            value: 2,
            playerId: "3294",
            team: "DAL",
            position: "QB",
            id: "86197778-8d4b-4eba-affe-08ef7be7c70b",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18055.png",
            positionOrder: 1,
        },
        {
            name: "Christian Kirk",
            value: 8,
            playerId: "4950",
            team: "JAX",
            position: "WR",
            id: "ebcd87ce-218c-4144-810b-921c2f59d6e8",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19815.png",
            positionOrder: 3,
        },
        {
            name: "Allen Lazard",
            value: 8,
            playerId: "5185",
            adr: 12,
            adp: 115,
            team: "NYJ",
            position: "WR",
            id: "6a23db75-021b-4808-99e6-21a33d34202b",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20145.png",
            positionOrder: 3,
        },
        {
            name: "D.K. Metcalf",
            value: 4,
            playerId: "5846",
            team: "SEA",
            position: "WR",
            id: "754faf0f-40f7-45f0-b23b-6ce990ecaf26",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20875.png",
            positionOrder: 3,
        },
        {
            name: "Terry McLaurin",
            value: 0,
            playerId: "5927",
            adr: 6,
            adp: 50.5,
            team: "WAS",
            position: "WR",
            id: "7e8c4641-2beb-4213-ba22-69fe0307005f",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20873.png",
            positionOrder: 3,
        },
        {
            name: "Jakobi Meyers",
            value: 11,
            playerId: "5947",
            adr: 12,
            adp: 117.5,
            team: "LV",
            position: "WR",
            id: "73e194d1-a4b7-4de4-b1c2-3c24ef502918",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20876.png",
            positionOrder: 3,
        },
        {
            name: "Hunter Renfrow",
            value: 8,
            playerId: "5955",
            adr: 18,
            adp: 174,
            team: "LV",
            position: "WR",
            id: "34c523c7-bc58-49f0-a9cc-f9edd91fe00f",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20924.png",
            positionOrder: 3,
        },
        {
            name: "Chase McLaughlin",
            value: 10,
            playerId: "6650",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "TB",
            position: "K",
            id: "12d28404-63e1-432f-adde-c93631a5c39c",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21542.png",
            positionOrder: 5,
        },
        {
            name: "Jonathan Taylor",
            value: 0,
            playerId: "6813",
            adr: 2,
            adp: 13.5,
            team: "IND",
            position: "RB",
            id: "925195a4-06ba-4e37-ae7d-a3d6a5419139",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21682.png",
            positionOrder: 2,
        },
        {
            name: "Travis Etienne",
            value: 3,
            playerId: "7543",
            team: "JAX",
            position: "RB",
            id: "970693f0-0af4-4627-ac0c-bf519f7433ee",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21696.png",
            positionOrder: 2,
        },
        {
            name: "Elijah Mitchell",
            value: 4,
            playerId: "7561",
            adr: 13,
            adp: 127.5,
            team: "SF",
            position: "RB",
            id: "8ba68abf-e9d2-4927-bf8d-476f271d840c",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22535.png",
            positionOrder: 2,
        },
        {
            name: "Alec Pierce",
            value: 16,
            playerId: "8142",
            team: "IND",
            position: "WR",
            id: "a67ee8f8-e9de-4fb9-90b6-edca2f83f6d8",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23232.png",
            positionOrder: 3,
        },
        {
            name: "Andy Dalton",
            value: 19,
            playerId: "829",
            isAdpCalculated: true,
            adr: 31,
            adp: 310,
            team: "CAR",
            position: "QB",
            id: "d2a0e5af-3850-4f16-8e40-a0b1d15c2ce1",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/12841.png",
            positionOrder: 1,
        },
        {
            name: "Arizona Cardinals",
            value: 10,
            playerId: "ARI",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "ARI",
            position: "DEF",
            positionOrder: 6,
        },
        {
            name: "Seattle Seahawks",
            value: 10,
            playerId: "SEA",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "SEA",
            position: "DEF",
            positionOrder: 6,
        },
    ],
    "NickAdamsUSA 4 President": [
        {
            name: "Justin Tucker",
            value: 14,
            playerId: "1264",
            team: "BAL",
            position: "K",
            id: "20a0bad2-d530-4ff4-a2df-5c0a21a1f5db",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/14688.png",
            positionOrder: 5,
        },
        {
            name: "Tyler Lockett",
            value: 9,
            playerId: "2374",
            team: "SEA",
            position: "WR",
            id: "dffa69ad-331e-4f09-ae38-40a5a4406be6",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/16830.png",
            positionOrder: 3,
        },
        {
            name: "Stefon Diggs",
            value: 0,
            playerId: "2449",
            adr: 1,
            adp: 8,
            team: "BUF",
            position: "WR",
            id: "a1c40664-b265-4083-aad2-54b4c734f2c5",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/16906.png",
            positionOrder: 3,
        },
        {
            name: "Raheem Mostert",
            value: 14,
            playerId: "2749",
            isAdpCalculated: true,
            adr: 16,
            adp: 158,
            team: "MIA",
            position: "RB",
            id: "b040e601-ec40-4757-bf3d-71bf64ef99cf",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/17217.png",
            positionOrder: 2,
        },
        {
            name: "Tyler Boyd",
            value: 11,
            playerId: "3225",
            team: "CIN",
            position: "WR",
            id: "76a5edec-5ff7-49fa-a8ec-5768a372279d",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/17986.png",
            positionOrder: 3,
        },
        {
            name: "Deshaun Watson",
            value: 16,
            playerId: "4017",
            team: "CLE",
            position: "QB",
            id: "eec5265c-7731-4bb6-8af2-4f98a67f9ab7",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18857.png",
            positionOrder: 1,
        },
        {
            name: "Jamaal Williams",
            value: 11,
            playerId: "4149",
            isAdpCalculated: true,
            adr: 13,
            adp: 126,
            team: "NO",
            position: "RB",
            id: "122e131c-b08c-4b10-901d-481a20aeffb8",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18995.png",
            positionOrder: 2,
        },
        {
            name: "Robert Tonyan",
            value: 19,
            playerId: "4602",
            isAdpCalculated: true,
            adr: 29,
            adp: 281,
            team: "CHI",
            position: "TE",
            id: "7c9c7800-69d0-459b-812b-a07ac48e9f2a",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19491.png",
            positionOrder: 4,
        },
        {
            name: "Hayden Hurst",
            value: 19,
            playerId: "4973",
            isAdpCalculated: true,
            adr: 20,
            adp: 196,
            team: "CAR",
            position: "TE",
            id: "1b125fc4-5dd9-4eb9-a42f-048e61ca42b7",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19843.png",
            positionOrder: 4,
        },
        {
            name: "Nick Chubb",
            value: 0,
            playerId: "4988",
            adr: 3,
            adp: 23,
            team: "CLE",
            position: "RB",
            id: "4bd60b33-9fbf-4156-ba2b-8264ac37b418",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19798.png",
            positionOrder: 2,
        },
        {
            name: "Marquise Brown",
            value: 7,
            playerId: "5848",
            adr: 8,
            adp: 72.5,
            team: "ARI",
            position: "WR",
            id: "feeee40a-dd63-41a7-89cd-6c95b5456833",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21045.png",
            positionOrder: 3,
        },
        {
            name: "Kyler Murray",
            value: 2,
            playerId: "5849",
            team: "ARI",
            position: "QB",
            id: "dd5a6b6e-ffae-45a5-b8e6-718a9251f374",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20889.png",
            positionOrder: 1,
        },
        {
            name: "Josh Jacobs",
            value: 3,
            playerId: "5850",
            team: "LV",
            position: "RB",
            id: "61694ab9-b099-408e-b48d-6a643dd069ec",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20824.png",
            positionOrder: 2,
        },
        {
            name: "Gardner Minshew",
            value: 19,
            playerId: "6011",
            isAdpCalculated: true,
            adr: 33,
            adp: 327,
            team: "IND",
            position: "QB",
            id: "dabb52c0-455b-48fe-996b-abf758120623",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20880.png",
            positionOrder: 1,
        },
        {
            name: "Donovan Peoples-Jones",
            value: 16,
            playerId: "6824",
            isAdpCalculated: true,
            adr: 15,
            adp: 148,
            team: "CLE",
            position: "WR",
            id: "924edb03-29a9-42ae-92dd-ef7e8a498095",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21754.png",
            positionOrder: 3,
        },
        {
            name: "Jalen Hurts",
            value: 2,
            playerId: "6904",
            team: "PHI",
            position: "QB",
            id: "64bd0f02-6a5d-407e-98f1-fd02048ea21d",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21831.png",
            positionOrder: 1,
        },
        {
            name: "Greg Dulcich",
            value: 17,
            playerId: "8172",
            isAdpCalculated: true,
            adr: 16,
            adp: 150.5,
            team: "DEN",
            position: "TE",
            id: "b9e4a022-d15c-4cef-9879-170277f17207",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/23310.png",
            positionOrder: 4,
        },
        {
            name: "Denver Broncos",
            value: 10,
            playerId: "DEN",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "DEN",
            position: "DEF",
            positionOrder: 6,
        },
        {
            name: "Tampa Bay Buccaneers",
            value: 10,
            playerId: "TB",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "TB",
            position: "DEF",
            positionOrder: 6,
        },
    ],
    "Hocked and Loaded ": [
        {
            name: "Ryan Tannehill",
            value: 10,
            playerId: "1049",
            team: "TEN",
            position: "QB",
            id: "5812204c-6dae-4450-8011-99e0f72864ac",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/13799.png",
            positionOrder: 1,
        },
        {
            name: "Adam Thielen",
            value: 7,
            playerId: "1689",
            team: "CAR",
            position: "WR",
            id: "2fa2b2da-4aa9-44b5-b27e-56876dfe2ad4",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/15534.png",
            positionOrder: 3,
        },
        {
            name: "Jerick McKinnon",
            value: 15,
            playerId: "2161",
            isAdpCalculated: true,
            adr: 14,
            adp: 132.5,
            team: "KC",
            position: "RB",
            id: "f77479d7-51a5-41f9-8924-69526dd078cd",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/16510.png",
            positionOrder: 2,
        },
        {
            name: "Leonard Fournette",
            value: 3,
            playerId: "3969",
            team: null,
            position: "RB",
            id: "7f46a7be-286e-4bfe-8778-d03dbe600ce9",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18803.png",
            positionOrder: 2,
        },
        {
            name: "D'Onta Foreman",
            value: 17,
            playerId: "4111",
            isAdpCalculated: true,
            adr: 16,
            adp: 155,
            team: "CHI",
            position: "RB",
            id: "02779042-2b4e-4fa9-b598-364fe01b523a",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18957.png",
            positionOrder: 2,
        },
        {
            name: "Mack Hollins",
            value: 19,
            playerId: "4177",
            isAdpCalculated: true,
            adr: 26,
            adp: 252,
            team: "ATL",
            position: "WR",
            id: "93cb5790-1012-4c42-bccb-5748c27ba7d6",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19023.png",
            positionOrder: 3,
        },
        {
            name: "Aaron Jones",
            value: 0,
            playerId: "4199",
            adr: 6,
            adp: 54.5,
            team: "GB",
            position: "RB",
            id: "27dd5b6e-ea65-4622-a6b4-460fd144407c",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19045.png",
            positionOrder: 2,
        },
        {
            name: "Josh Allen",
            value: 0,
            playerId: "4984",
            adr: 3,
            adp: 20.5,
            team: "BUF",
            position: "QB",
            id: "3069db07-aa43-4503-ab11-2ae5c0002721",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19801.png",
            positionOrder: 1,
        },
        {
            name: "T.J. Hockenson",
            value: 6,
            playerId: "5844",
            team: "MIN",
            position: "TE",
            id: "bd1120b6-38b3-4225-a4b0-20660a149d0d",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20805.png",
            positionOrder: 4,
        },
        {
            name: "A.J. Brown",
            value: 2,
            playerId: "5859",
            team: "PHI",
            position: "WR",
            id: "a9e580f2-1fbe-46fb-887c-c84089b507e4",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21042.png",
            positionOrder: 3,
        },
        {
            name: "Darius Slayton",
            value: 19,
            playerId: "6149",
            isAdpCalculated: true,
            adr: 22,
            adp: 215.5,
            team: "NYG",
            position: "WR",
            id: "82ed30a5-54a8-4ed0-b040-99c3a78fb055",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20943.png",
            positionOrder: 3,
        },
        {
            name: "Tua Tagovailoa",
            value: 4,
            playerId: "6768",
            team: "MIA",
            position: "QB",
            id: "26ad9c27-de38-495e-913c-6fb2428e76d3",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21677.png",
            positionOrder: 1,
        },
        {
            name: "CeeDee Lamb",
            value: 0,
            playerId: "6786",
            adr: 2,
            adp: 12.5,
            team: "DAL",
            position: "WR",
            id: "a72ea15b-5199-4101-a300-846e1c655add",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21679.png",
            positionOrder: 3,
        },
        {
            name: "Chase Claypool",
            value: 19,
            playerId: "6886",
            isAdpCalculated: true,
            adr: 20,
            adp: 199,
            team: "CHI",
            position: "WR",
            id: "53ed110c-f022-4759-afd3-1cd3436dbba7",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21752.png",
            positionOrder: 3,
        },
        {
            name: "Antonio Gibson",
            value: 3,
            playerId: "6945",
            team: "WAS",
            position: "RB",
            id: "c0a8a5d0-583f-457a-9d96-70027d3f69e7",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21861.png",
            positionOrder: 2,
        },
        {
            name: "Evan McPherson",
            value: 10,
            playerId: "7839",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "CIN",
            position: "K",
            id: "acc143ed-53b2-49c9-81bc-16e6c98ffcae",
            image: "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22908.png",
            positionOrder: 5,
        },
        {
            name: "Baltimore Ravens",
            value: 15,
            playerId: "BAL",
            team: "BAL",
            position: "DEF",
            positionOrder: 6,
        },
        {
            name: "New York Giants",
            value: 10,
            playerId: "NYG",
            isAdpCalculated: true,
            adr: 9,
            adp: null,
            team: "NYG",
            position: "DEF",
            positionOrder: 6,
        },
    ],
};

const PlayerRow = ({
    position,
    name,
    id,
    team,
    value,
    isAdpCalculated,
    image,
}) => {
    return (
        <div className={styles.playerRow}>
            <div className={styles.left}>
                <div className={classNames(styles.position, styles[position])}>
                    {position}
                </div>
                <div className={styles.image}>
                    <img className={styles.img} src={image} />
                </div>
                <div className={styles.name}>{name}</div>
                <div className={styles.team}>({team || "--"})</div>
            </div>
            <div className={classNames(styles.right)}>
                <div
                    className={classNames(styles.cost, !value && styles.noKeep)}
                >
                    {value ? (
                        <>
                            <div>{value}</div>
                            <div> {getNumberSuffix(value)}</div>
                        </>
                    ) : (
                        "X"
                    )}
                    {isAdpCalculated && (
                        <div className={styles.adpTooltip}>*</div>
                    )}
                </div>
                <div className={styles.helpTooltip}>?</div>
            </div>
        </div>
    );
};

const Main = () => {
    const [activeTab, setActiveTab] = useState("Rules");
    const [selected, setSelected] = useState("All");

    const keeperData = data[selected];

    return (
        <>
            <div className={styles.title}>
                Your Mom's Favorite League Companion Site
            </div>
            <div className={styles.main}>
                <div className={styles.tabs}>
                    {["Rules", "Keeper Lottery"].map((label) => {
                        return (
                            <Tab
                                key={label}
                                label={label}
                                selected={activeTab === label}
                                onClick={() => setActiveTab(label)}
                            />
                        );
                    })}
                </div>
                <SliderSelect
                    options={Object.keys(data)}
                    selected={selected}
                    setSelected={setSelected}
                />
                <div className={styles.body}>
                    <div>
                        <div className={styles.teamRow}>
                            <div className={styles.teamImage}></div>
                            <div className={styles.teamName}>{selected}</div>
                        </div>
                    </div>
                    {_.sortBy(
                        keeperData,
                        ["positionOrder", "value"],
                        ["desc", "desc"]
                    ).map((player) => (
                        <PlayerRow key={player.id} {...player} />
                    ))}
                </div>
            </div>
        </>
    );
};

export default Main;
